### ISSUE TITLE
ViewBag and ViewData access needed in handler

### ISSUE THREAD

**Issue by Lanayx** [giraffe-fsharp/Giraffe.Razor#5]
Looks now there no way how I can pass ViewBag and ViewData to _razorView_ or _razorHtmlView_ to be rendered inside the view.

**Comment by dustinmoris** [comment]
Can you give me an example? Nothing has really changed since the last version except that I've updated to the latest version of Giraffe and ASP.NET Core. Maybe something changed in ASP.NET Core MVC for razor views?

**Comment by Lanayx** [comment]
No, nothing changed =) My concern is that you can only pass a model inside razorView function, not the ViewData object. In regular MVC framework you can access ViewData and TempData inside controller and in Giraffe handlers we don't have controllers to use these objects.

**Comment by dustinmoris** [comment]
Oh, ok I see what you mean. Personally I am of the believe that strongly typed view models are always preferred to the generic `ViewData` or `ViewBag` or `TempData` collection types, but if you think this is a much desired feature then we can think of changing the current handlers.

In principle, there's nothing you can't do with strongly typed view models though.

This [Microsoft article](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.1#passing-data-to-views) explains very well the different approaches of passing data to a Razor view.

It specifically mentions that view models are actually the "better" option of the bunch and also [mentions that some developers even choose to never use ViewData](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.1#weakly-typed-data-viewdata-viewdata-attribute-and-viewbag) because of potetial runtime issues it may cause.

I personally find that most developers use `ViewData` for data which is commonly used across all views, but were too lazy to create a `BaseViewModel` class which other view models can derive from. This OO approach would give you the same effect as the `ViewData` option, except it would have all the benefits of being a strongly typed class. I think when it comes to data models an inheritance model with classes in F# is a reasonable workaround as well while there is no inheritance for record types yet.

But that's just my opinion, what do you think? Do you reckon the ViewData property should still be exposed in Giraffe?

**Comment by Lanayx** [comment]
I agree with you in most points except that it is a good practice to create a `BaseViewModel`, since not all models should share the same common fields and in general inheritance is better to be avoided. Also specifically to F#, I use records whenever possible, and I'm reluctant to define class instead. Regarding Microsoft guidelines in the [very basic sample](https://github.com/aspnet/Mvc/blob/release/2.2/samples/MvcSandbox/Views/Shared/_Layout.cshtml) they use `ViewData` for some data that travels through multiple views. From my experience, even when the data is not shared between views it's sometimes convenient to use `ViewData` for some non-domain data like page number or debug info or trace info.

**Comment by dustinmoris** [comment]
Ok, I agree with you it would be good to expose the ViewData and ViewBag here as well.

**Comment by dustinmoris** [comment]
This is being currently built on the CI server and subsequently pushed to NuGet. Thanks for raising this issue and helping with the implementation!
